<?php
/** @var \Mtools\Core\Block\System\Config\Modules $block */
/** @var \Magento\Framework\Escaper $escaper */

$escaper = $escaper ?? $block; // Magento 2.3-2.4 difference
?>
<style>
    .mtools-modules{
        padding-left: 50px;
    }
    .mtools-modules th{
        text-align: left;
    }
</style>
<div class="mtools-modules">
    <table>
        <tr>
            <th><?= $escaper->escapeHtml(__('Module Name')) ?></th>
            <th><?= $escaper->escapeHtml(__('Module Version')) ?></th>
            <th><?= $escaper->escapeHtml(__('Is Active')) ?></th>
        </tr>
        <?php foreach ($block->getModules() as $module): ?>
        <tr>
            <td><?= $escaper->escapeHtml($module['name']) ?></td>
            <td><?= $escaper->escapeHtml($module['version']) ?></td>
            <td><?= $escaper->escapeHtml((bool)(int)$module['active'] ? __('Yes') : __('No')) ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
